# Generated by Django 6.0.6 on 2026-06-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvariant',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=8, default=5, max_digits=20),
        ),
    ]
